ui: mocha-bdd
local: 8080
browserify:
  - transform:
      name: babelify
      presets: es2015
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: firefox
    version: latest
html: ./.zuul.html